# Generated by Django 3.1.6 on 2021-02-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210210_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
    ]
