# Generated by Django 3.1.6 on 2021-02-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210210_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
