# Generated by Django 3.1.6 on 2021-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_seat_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='nametrip', max_length=120),
            preserve_default=False,
        ),
    ]
